# install system package
dist: xenial
sudo: required

before_install:
  - sudo apt-get -q update -y
  - sudo apt-get -q install python-tk -y
  - sudo apt-get -q install build-essential -y 
  - sudo apt-get -q install libssl-dev -y
  - sudo apt-get -q install libcurl4-gnutls-dev 
  - sudo apt-get -q install libexpat1-dev 
  - sudo apt-get -q install gettext 
  - sudo apt-get -q install unzip -y
  - sudo apt-get -q install libc6 -y
  - sudo apt-get install python-dev -y

# pick languages
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "pip install coveralls"
  - "pip install jinja2"
  - "./.travis.sh"
  - "python -m spacy download en" 

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

# command to run tests
script: 
  # - "python ./test_script.py"
  - "coverage run --source=autonomio ./test_script.py"
  #- "coverage run -m autonomio.commands.data random_twitter"

after_success:
  coveralls
